from .nodes import TSK_CLASS_MAPPINGS, TSK_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TSK_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TSK_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

